require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'config/**/*'
    - 'db/schema.rb'
    - Gemfile
    - Rakefile
    - config.ru
    - 'db/migrate/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/routes.rb'

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

# Style/AsciiComments:
#   Enabled: false
